# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "issues"
    label: "Issues"
    folder: "_issues"
    sort: "title:desc"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          required: true,
          default: "page",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Intro Paragraph",
          name: "intro_paragraph",
          widget: "string",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          required: true,
          hint: "Issues are sorted by order number. Lower order numbers show up higher in the list of issues. Multiple issues can have the same order number.",
        }
  - name: "news"
    label: "News"
    folder: "_news"
    sort: "date:desc"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Link", name: "link", widget: "string", required: true }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          tagname: "h1",
          required: true,
        }
      - {
          label: "Publication",
          name: "publication",
          widget: "string",
          required: true,
        }
      - {
          label: "Date",
          name: "date",
          widget: "date",
          format: "YYYY-MM-DD",
          required: true,
        }
      - { label: "Logo", name: "logo", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }
  - label: "Copy"
    name: "copy"
    files:
      - label: "Home"
        name: "home"
        file: "_data/home.yml"
        fields:
          - { label: "Main title", name: "hero", widget: "string" }
          - {
              label: "Main Description",
              name: "hero-description",
              widget: "text",
            }
          - { label: "Intro", name: "intro", widget: "text" }
          - {
              label: "Intro button text",
              name: "intro_button_text",
              widget: "string",
            }
          - { label: "Issues title", name: "issue_title", widget: "string" }
          - {
              label: "Issues description",
              name: "issue_description",
              widget: "text",
            }
          - {
              label: "Issues button text",
              name: "issue_button_text",
              widget: "string",
            }
          - { label: "Donate title", name: "donate_title", widget: "string" }
          - {
              label: "Donate description",
              name: "donate_description",
              widget: "text",
            }
          - { label: "News title", name: "news_title", widget: "string" }
          - {
              label: "News button text",
              name: "news_button_text",
              widget: "string",
            }
          - {
              label: "District title",
              name: "district_title",
              widget: "string",
            }
          - {
              label: "District description",
              name: "district_description",
              widget: "text",
            }
      - label: "Issues"
        name: "issues"
        file: "_data/issues.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", tagname: "h1" }
          - {
              label: "Intro Paragraph",
              name: "intro_paragraph",
              widget: "text",
              required: true,
            }
      - label: "News"
        name: "news"
        file: "_data/news.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", tagname: "h1" }
          - {
              label: "Intro Paragraph",
              name: "intro_paragraph",
              widget: "text",
              required: true,
            }
      - label: "About"
        name: "about"
        file: "_data/about.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", tagname: "h1" }
          - {
              label: "Intro Paragraph",
              name: "intro_paragraph",
              widget: "text",
              required: true,
            }
          - { label: "Body", name: "body", widget: "markdown", required: true }
          - { label: "Photo", name: "photo", widget: "image", required: true }
      - label: "Footer"
        name: "footer"
        file: "_data/footer.yml"
        fields:
          - {
              label: "Paid for by",
              name: "paidfor",
              widget: "string",
              required: true,
            }
          - {
              label: "Address",
              name: "address",
              widget: "text",
              required: true,
            }
          - { label: "Email", name: "email", widget: "string", required: true }
          - {
              label: "Twitter",
              name: "twitter",
              widget: "string",
              required: true,
            }
          - {
              label: "Facebook",
              name: "facebook",
              widget: "string",
              required: true,
            }
          - {
              label: "Instagram",
              name: "instagram",
              widget: "string",
              required: true,
            }
          - {
              label: "Privacy policy URL",
              name: "privacy",
              widget: "string",
              required: true,
            }
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - { label: Text, name: text, widget: string }
              - { label: Url, name: url, widget: string }
  - name: "Pages"
    label: "Pages"
    folder: "pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Permalink",
          name: "permalink",
          widget: "string",
          hint: "Changing the permalink will change the url for this page; note that this will break any links to the old url",
        }
      - {
          label: "Intro Paragraph",
          name: "intro_paragraph",
          widget: "string",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
